config/routes.rb
RoRPMS::Application.routes.draw do

  root 'projects#show'

    resources :projects do
      resources :students
    end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
  
  def show
    @projects = Project.all
  end
  
  def create
    @project = Project.new(project_params)
    @project.status = "Waiting"
    @project.save
    redirect_to root_path
  end
  
  def new
    @project = Project.new(params[:id])
    @project.status = "Waiting"
    @project.save
    redirect_to root_path
  end
  
  private
    def project_params
      params.require(:project).permit(:title, :lecturer)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @student = @project.students.create(params[:student])
    @student.save
  end
  
  def new
    @project = Project.find(params[:project_id])
    @student = @project.students.create(params[:student])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRPMS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/new.html.erb
<h1>Add new project</h1>

<%= form_for :project, url: projects_path do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :lecturer %>
		<%= f.text_field :lecturer %>
	</p>
		<%= form_for([@project, @project.students.build]) do |s| %>
		  <p>
		    <%= s.label :name %><br />
		    <%= s.text_field :name %>
		  </p>
		<% end %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/projects/show.html.erb
<h1>pms</h1>

<%= link_to "Create Project", [@project, new_project_student_path] %>

<table border="1">
  <tr>
	<th>Lp.</th>
    <th>Title</th>
    <th>Lecturer</th>
	<th>Creation date</th>
	<th>Status</th>
	<th>Students</th>
  </tr>
 
  <% @projects.each_with_index do |p, i| %>
    <tr>
		<td><%= (i+1) %>.</td>
		<td><%= p.title %></td>
		<td><%= p.lecturer %></td>
		<td>
			<%= p.created_at.localtime.strftime(format='%F') %><br>
			<%= p.created_at.localtime.strftime(format='%R') %>
		</td>
		<td><%= p.status %></td>
		<td>
			<ul>
				<% p.students.each do |student| %>
					<li><%= student.name %></li>
				<% end %>
			</ul>
		</td>
    </tr>
  <% end %>
</table>